# Generated by Django 4.1.7 on 2023-02-27 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import video_upload.models
import video_upload.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(null=True, storage=video_upload.models.OverwriteStorage(), upload_to=video_upload.utils.hash_thumbnail_filename)),
                ('video', models.FileField(null=True, storage=video_upload.models.OverwriteStorage(), upload_to=video_upload.utils.hash_video_filename)),
                ('uploaded_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-id'],
            },
        ),
    ]
